version: "3"
services:
  app:
    container_name: dalalbull
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./:/excelplay-backend-dalalbull
    depends_on:
      - db
    networks:
      - dalalbull_network

  db:
    image: postgres:latest
    container_name: dalalbull_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - dalalbull_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - dalalbull_network
    restart: unless-stopped

volumes:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  dalalbull_network:
    driver: bridge
